### PR TITLE
Mnemonic Word Generation and Confirmation

### PR DESCRIPTION
**Pull request by mrmetech**
This adds a confirmation that the user has written down their mnemonic words and also Adds two start calls -generateseed and -importseed. -importseed replaced -phraseseed as well.

### CODE REVIEW

**Comment by presstab** [comment]
This code looks oddly familiar.

**Comment by jonspock** [comment]
> This code looks oddly familiar.

It was acknowledged that the code wasn't all original but also stated that no copyrights were removed from the code.

**Comment by presstab** [comment]
Sure, that's a good step towards being within MIT open source license, but still is not. All of the files that use blocks of code from other projects would need to add that copyright at the top of the file too. 

There is really no good reason that a really cool new project should start off out of compliance with open source licensing, it could end up slowing it down in the long term if it does.

I am not trying to be a license Nazi, but I really do like getting credit for my work (and others probably do as well). As far as I see the only work here that is kolbys is the IDE settings for clion that were incidentally included.

**Comment by giaki3003** [comment]
I'm with old tabby on this one, let a man get his bread

**Comment by jonspock** [comment]
Please add the copyrights to the files in your repo and we shall copy. It's not our job to add copyrights for you. If an unchanged public domain file was added to your repo its license does not change by that act.  Each file should have a copyright or reference such. There are several copyrights in your COPYING that likely do NOT apply to these files

**Comment by presstab** [comment]
I am talking about files like bitcoingui.cpp and others that do have copyright. It's always easier to have these changed while it is still a pull request. Also think the PR should have the IDE specific files removed, it makes it difficult for me to checkout this code since I use clion.

**Comment by jonspock** [comment]
Ah OK. I agree and missed that point.  @mrmetech please note @presstab's comment

**Comment by mrmetech** [comment]
> I am talking about files like bitcoingui.cpp and others that do have copyright. It's always easier to have these changed while it is still a pull request. Also think the PR should have the IDE specific files removed, it makes it difficult for me to checkout this code since I use clion.

You didn't even add your own copyright notice on bitcoingui.cpp so it takes what you said into question if you cant do what you asked on your own repo. I mean I can add it, but you should probably do what you are telling me to, when you haven't done it yourself.

**Comment by mrmetech** [comment]
image
Cough cough. Am just saying you didn't add it to your own file.

**Pull request closed without merging**
