### PR TITLE
Update various 'label' RPC functions

### PR DESCRIPTION
**Pull request by jonspock**
Mostly just commit fix ups. Not yet tested

### CODE REVIEW

**Comment by pppest** [comment]
getaddressinfo
Issue: Method not found (code -32601)

getlabeladdress
- WORKS

getaddressesbylabels
- WORKS.

getreceivedbylabel
- WORKS

listlabels
- ISSUE: Method not found (code -32601)

listreceivedbylabel
- WORKS

setlabel
- WORKS. but adds a second label if you set a label for an address that already has a label. should it have an option to specify if user wants to add an extra label or to replace?

listwalletdir
- WORKS

listwallets
- WORKS.

**Comment by jonspock** [comment]
Neither addressinfo and listlabels gave me a "Method not found" error

**Comment by pppest** [comment]
listlabels
version

**Comment by pppest** [comment]
gimpit

**Comment by pppest** [comment]
notfound

**Comment by pppest** [comment]
notfound

**Comment by jonspock** [comment]
What commit is your build based on @pppest ? I dont' see that Client Version hash anywhere. Can you retry now with `develop` branch?

**Comment by pppest** [comment]
was from testing-314. git fetch origin pull/311/head:testing-314. 
build now from develop branch.
listlabels and getaddressinfo confimed working in that build.

**Comment by pppest** [comment]
also in the develop build setlabel replaces the label correctly.

**Pull request merged**
