### PR TITLE
Start-Up Dialog GUI

### PR DESCRIPTION
**Pull request by proteanx**
Applied GUI theme to seedphrase dialog, expanded the first-run setpassphrasedialog to be more friendly/helpful, updated various QT strings. I still have some work to do, especially on the final drag and drop verification page but wanted to get a PR in for what's done thus far and get some feedback.

Screenshot from 2019-07-16 13-34-36

Screenshot from 2019-07-16 13-34-43

Screenshot from 2019-07-16 13-34-49

Screenshot from 2019-07-16 13-35-18

Screenshot from 2019-07-16 13-35-25

### CODE REVIEW

**Comment by jonspock** [comment]
Looks great. Will try out. Small nit on the wording. "Your passphrase can always unlock uncorrupted wallet files, but in the event of corruption only a seed phrase can restore the wallet" or something like that.

**Comment by proteanx** [comment]
> Looks great. Will try out. Small nit on the wording. "Your passphrase can always unlock uncorrupted wallet files, but in the event of corruption only a seed phrase can restore the wallet" or something like that.

Thanks, wording should be fixed now

**Comment by jonspock** [comment]
When drag and dropping words to verify I noticed that only some words got colorized to blue when used.
Will wait on resolution with others before actually reviewing code.
Also why close on Password cancel instead of previous Application quit?
I think there should be a way to escape the process at any point too if possible

**Comment by proteanx** [comment]
Replaced by #183

**Pull request closed without merging**
